#Travis CI build configuration
language: python
python:
  "3.8"
#help: https://stackoverflow.com/questions/35972415/python-import-fails-on-travisci-but-not-locally  
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
script:
#The command "sonar-scanner" exited with 1: https://travis-ci.org/ZNClub-PA-ML-AI/OctoPy-Predictor/builds/635588777#L594
#  - sonar-scanner
  - pytest
addons:
  sonarcloud:
    organization: "PA-ML-AI"
    token:
      secure: "19f1dfde5153cc1745a9e0fe469be20ccfd67ce7"
